---

redis_user: redis
redis_group: '{{ redis_user }}'

redis_master_auth: ahihi

redis_install_dir: /opt/redis
redis_master_ip: 192.168.122.129 
redis_master_port: 6379



#Config Redis Sentinel
redis_sentinel_port: 26379


