---
# handlers file for redis-all-in-one
- name: "restart redis"
  service:
    name: redis
    state: restarted
  become: true

- name: "stop redis"
  service:
    name: redis
    state: stoped
  become: true

- name: "start redis"
  service:
    name: redis
    state: started
  become: true

