---
# defaults file for redis-all-in-one
redis_version: 6.2.6

redis_user: redis
redis_group: '{{ redis_user }}'

turning_redis: true

# when true then install .rpm file
install_dependencies: false
package_names:
  - cpp-4.8.5-44.el7.x86_64
  - gcc-4.8.5-44.el7.x86_64
  - glibc-2.17-317.el7.x86_64
  - glibc-common-2.17-317.el7.x86_64
  - glibc-devel-2.17-317.el7.x86_64
  - glibc-headers-2.17-317.el7.x86_64
  - kernel-headers-3.10.0-1160.el7.x86_64
  - libgcc-4.8.5-44.el7.x86_64
  - libgomp-4.8.5-44.el7.x86_64
  - libmpc-1.0.1-3.el7.x86_64
  - mpfr-3.1.1-4.el7.x86_64


#
redis_install_dir: /opt/redis
redis_accesslist_enable: false

#Config Redis Master
redis_master_port: 6379
redis_master_bind: 0.0.0.0
redis_master_ip: 192.168.122.129
redis_master_auth: ahihi
redis_master_user: false

#Config Redis Slave
redis_slave_port: 6379
redis_slave_bind: 0.0.0.0
redis_slave_ip: 192.168.122.128
redis_slave_replicaof: false
redis_slave_masterauth: '{{ redis_master_auth }}'
redis_slave_masteruser: '{{ redis_master_user }}'


#Config Redis Sentinel
redis_sentinel_port: 26379
