- name: Create upload folder setup
  file:
    path: /setup
    state: directory
    mode: '0755'

- name: Upload package require
  copy:
    src: "{{ item }}.rpm"
    dest: /setup/
  loop: "{{ package_names }}"

- name: Install RPM
  shell: rpm -Uvh --reinstall /setup/{{ item }}.rpm
