---
# tasks file for roles/redis_single

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /setup
    state: directory
    mode: '0755'

- name: Download redis version {{ version }}
  get_url:
    url: https://download.redis.io/releases/redis-{{ version }}.tar.gz
    dest: /setup/
    mode: '0640'

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: /setup/redis-{{ version }}.tar.gz
    dest: /setup/
    remote_src: yes

- name: create redis group
  group: name=redis state=present system=yes

- name: create redis user
  user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

- name: make sure that folder exists /opt/redis/{{ item }}
  file: path=/opt/redis/{{ item }} state=directory mode=0755
  loop: 
    - conf
    - bin
    - logs
    - data
  become: true

- name: build redis
  shell: "cd /setup/redis-{{ version }} ; make"
  become: true

- name: installing redis binaries
  shell: /bin/cp -f /setup/redis-{{ version }}/src/{{ item }} /usr/local/bin/
  loop:
    - redis-server
    - redis-cli
    - redis-sentinel
    - redis-benchmark
  become: true
